In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [4]:
print(arr[0])

10


In [5]:
print(arr[-1])

50


In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
arr2.shape

(2, 3)

In [8]:
print(arr2.shape)

(2, 3)


In [9]:
arr2.sum()

np.int64(21)

In [10]:
arr2.max()

np.int64(6)

In [11]:
arr2.min()

np.int64(1)

In [12]:
arr2.mean()

np.float64(3.5)

In [13]:
#Reshape Array

In [16]:
a = np.array([1,2,3,4,5,6])

b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a = np.array([10,20,30])
b = np.array([1,2,3])

(a+b)

array([11, 22, 33])

In [18]:
#Find Even Number

In [19]:
a = np.array([1,2,3,4,5,6,7,8])
(a[a%2==0])

array([2, 4, 6, 8])

In [20]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [23]:
a=np.array([10,20,30,40,50])
print(a[0])
print(a[2])

10
30


In [24]:
#Array Slicing

In [25]:
a=np.array([10,20,30,40,50])
print(a[1:4])

[20 30 40]


In [29]:
a=np.array([[1,2,3],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a.shape

(2, 3)

In [27]:
a.size

6

In [32]:
print(np.sum(a))

21


In [34]:
a.max()

np.int64(6)

In [35]:
a.min()

np.int64(1)

In [36]:
a.mean()

np.float64(3.5)

In [37]:
a=np.array([10,20,30,40])
(a*2)

array([20, 40, 60, 80])

In [40]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# 0 Array
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [42]:
a=np.array([12,25,8,40,15,60])
a

array([12, 25,  8, 40, 15, 60])

In [47]:
print(len(a))

6


In [48]:
print(a.dtype)

int64


In [49]:
a.size

6

In [50]:
a.shape

(6,)

In [52]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a.shape

(2, 3)

In [55]:
a=np.array([[1,2,3],[4,5,6]])
a[0,1]

np.int64(2)

In [56]:
#Mathematical Operations

In [64]:
a1=np.array([10,20,30])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
#Add
(a1+5)

array([15, 25, 35])

In [66]:
#Sub
(a1-5)

array([ 5, 15, 25])

In [68]:
#Mul
(a1*2)

array([20, 40, 60])

In [70]:
#Div
(a1/2)

array([ 5., 10., 15.])

In [71]:
#Sum
(np.sum(a1))

np.int64(60)

In [72]:
#Max
(np.max(a1))

np.int64(30)

In [73]:
#Min
(np.min(a1))

np.int64(10)

In [74]:
#Average/Mean
(np.mean(a1))

np.float64(20.0)

In [75]:
#Zeros Array
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [76]:
#Ones Array
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [77]:
#Arange
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
#Even Numbers
a=np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [80]:
#Slicing
(a[1:4])

array([4, 6, 8])

In [82]:
#Array Reverse
a=np.array([10,20,30,40,50])
(a[::-1])

array([50, 40, 30, 20, 10])

In [84]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
# 0 to 20 Even Numbers
a=np.arange(0,21,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [88]:
# 1 to 10 Odd Numbers
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])